# Generated by Django 4.2 on 2024-05-25 21:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Estate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=40, verbose_name='title')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='price')),
                ('address', models.TextField(max_length=200, verbose_name='address')),
                ('city', models.CharField(max_length=40, verbose_name='city')),
                ('state', models.CharField(blank=True, max_length=40, verbose_name='state')),
                ('photo_main', models.ImageField(blank=True, upload_to='photos/%y/%m/%d/', verbose_name='photo_main')),
                ('photo_2', models.ImageField(blank=True, upload_to='photos/%y/%m/%d/', verbose_name='photo_2')),
                ('photo_3', models.ImageField(blank=True, upload_to='photos/%y/%m/%d/', verbose_name='photo_3')),
                ('landlord', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='landlord', to='users.landlord', verbose_name='landlord')),
            ],
            options={
                'verbose_name': 'estate',
                'verbose_name_plural': 'estates',
                'db_table': 'estate',
            },
        ),
    ]
