# Generated by Django 4.2 on 2024-05-27 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='estate',
            name='meterage',
            field=models.DecimalField(decimal_places=2, default=50, max_digits=20, verbose_name='meterage'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='estate',
            name='parking',
            field=models.BooleanField(default=True, verbose_name='parking'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='estate',
            name='storeroom',
            field=models.BooleanField(default=True, verbose_name='storeroom'),
            preserve_default=False,
        ),
    ]
